[package]
name = "deploy_scripts"
version = "0.0.1"

[lib]
sierra = true
casm = true

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = ["jediswap_v2_periphery::jediswap_v2_nft_position_manager::JediSwapV2NFTPositionManager", "jediswap_v2_periphery::jediswap_v2_swap_router::JediSwapV2SwapRouter"]

[dependencies]
starknet = "2.6.3"
sncast_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.20.1" }
jediswap_v2_periphery = { path = "../" }